name: telegram message
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Send telegram message on push request to review or push to master
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created pull request:
            Commit message: ${{ github.event.commits[0].message }}

            Repository: ${{ github.repository }}
            ${{ github.event.payload }}
            ${{ github.event.payload.pull_request }}
            ${{ github.event.payload.pull_request.title }}
            
            See changes: https://github.com/${{ github.repository }}/pull/${{github.event.number}}