name: telegram message
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Send telegram message on push request to review or push to master
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}