name: telegram message
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Send telegram message on push request to review or push to master
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}

            Repository: ${{ github.repository }}
            ${{ github.ref }}
            ${{ github.ref_name }}
            ${{ github.workflow }}
            ${{ github.action }}
            ${{ github.event }}
            ${{ github.event.commits }}
            ${{ github.event.name }}
            ${{ github.event.pash }}
            ${{ github.workspace }}
            ${{ github }}
            ${{ github.number }}
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}